### ISSUE TITLE
MySQL 5.7 boost 版本问题

### ISSUE THREAD

**Issue by DoopSky** [centos-bz/ezhttp#27]
config.sh 第101行
boost版本为1.59合适，1.66.0版本安装时编译会出问题
`boost_filename="boost_1_59_0"
set_md5 $boost_filename "51528a0e3b33d9e10aaa311d9eb451e3"
set_dl $boost_filename '
http://jaist.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz
'`

**Comment by laohoo666** [comment]
要改了，MYSQL5.7会闪退，然后进mysql看日志是这样
ezhttp 自动下载了1.66 
Boost minor version found is 66 we need 59

**Comment by DoopSky** [comment]
> 要改了，MYSQL5.7会闪退，然后进mysql看日志是这样
> ezhttp 自动下载了1.66
> Boost minor version found is 66 we need 59

打开 start.sh 加上 --no-screen 参数可以看到编译时输出的错误，不是闪退，只是退出了screen进程。
`./start.sh --no-screen`

**Comment by DoopSky** [comment]
已经修复了。
