### ISSUE TITLE
刚刚clone的最新代码，在centos 7.5上只安装php（最新版本）刚刚开始安装就会闪退

### ISSUE THREAD

**Issue by shishirui** [centos-bz/ezhttp#30]
后来clone了下来，再切换到一个旧版本时，安装就ok了。最新代码应该是有问题的。

**Comment by DoopSky** [comment]
上一个版本的代码是我提交的，确实有些错误。
等待Pull request 通过。

我自己在 Ubuntu 16.04.6 / 18.04.2 和 CentOS 6.10 / 7.6 上已经测试安装成功。

如果比较着急 可以先试试我修复版本 https://github.com/doopsky/ezhttp

**Comment by DoopSky** [comment]
自己排错的话 安装时运行脚本建议 加上 `--noscreen` 选择不使用screen，因为安装出现错误会直接关闭screen进程。
`./start.sh --noscreen`
